### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by Isetnt2** [ZEIW/ZEIW#1]
## Description
Error when building with yarn install
## Expected Behavior

Installed succesfully

## Actual Behavior

pi@raspberrypi:~/Documents/ZEIW $ yarn install
yarn install v1.16.0
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
error get-caller-file@2.0.5: The engine "node" is incompatible with this module. Expected version "6.* || 8.* || >= 10.*". Got "9.11.2"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

## Steps to Reproduce

All in terminal
Step 1: git clone https://github.com/zeiw/zeiw.git
Step 2:cd ./zeiw
Step 3: yarn install

## Context

Can't contribute to the project.
## Your Environment
Casper you know my set-up ;)

**Comment by pnfcre** [comment]
Issue resolved by installing latest LTS version of Node.
