### ISSUE TITLE
Player Settings doesn't recognized your logged in

### ISSUE THREAD

**Issue by MrCakeSlayer** [ZEIW/ZEIW#10]
## Description

When selecting 'Player Settings' and authorizing it with discord, it will close the pop ups and appear as though it worked (no errors get displayed), however, if you click the button again it asks you to log back in

## Expected Behavior

Either show options or display that your logged in, not sure what exactly is supposed to be displayed as it hasn't worked for me yet.

## Actual Behavior

It just continues to ask you to login after you have already authorized, refreshing and logging in again do not affect it.

## Steps to Reproduce

Step 1: Click player settings
Step 2: Click discord authorize button and authorize when prompted to
Step 3: Complete captcha
Step 4: Click player settings button again

## Context

Unable to access player settings 

## Your Environment

- Version used:
- Browser Name and version: Edge 44.17763.1.0
- Operating System and version: Windows 10 Home 10.0.17763 Build 17763

**Comment by ginkoid** [comment]
CNR
Edge 42.17134.10
Windows 10 Home 17134.829

**Comment by MrCakeSlayer** [comment]
https://www.youtube.com/watch?v=9SET6ANShNc&feature=youtu.be

**Comment by pnfcre** [comment]
@MrCakeSlayer Interesting, can you reproduce this bug in Edge private mode?

**Comment by MrCakeSlayer** [comment]
@pnfcre I just got to work and oddly edge isn't on this PC so it'll have to wait a few hours until I'm back on my home PC.

**Comment by pnfcre** [comment]
@MrCakeSlayer All right :+1:

**Comment by Mippy** [comment]
funny how im assigned but cant test it because you cant authorize apps while you have an unverified account 
![image](https://user-images.githubusercontent.com/26975085/61252457-7246c000-a712-11e9-8037-0f109344a122.png)

**Comment by Mippy** [comment]
Cannot Reproduce.

**Comment by Mippy** [comment]
I've determined this happens due to special characters in the user's Discord username. Since Discord doesn't support these characters in usernames, we're not supporting them either. Not a bug.

**Comment by pnfcre** [comment]
> due to popular demand i have made a workaround and you should be a ble to login now lol
- Isabel
