### ISSUE TITLE
Support ultra-wide monitors

### ISSUE THREAD

**Issue by pnfcre** [ZEIW/ZEIW#12]
## Detailed Description

Long story short: Ultra-wide monitors completely borks the UI in many ways. Currently unsupported, this FR wants to support it.

## Context

People actually use ultra-wide monitors.

## Possible Implementation

Refactor the CSS.

**Comment by MrCakeSlayer** [comment]
In regards to the particle animation in the background this has the same issue on my 4K display as it did on the ultra-wide monitor. (No particles on right side of screen, just solid black)

**Comment by awildtalon** [comment]
I assume that the developers cannot fix this. Instead, it's related to a software issue?

**Comment by pnfcre** [comment]
I actually think I can fix this with some effort :P

**Comment by awildtalon** [comment]
Aha! That's very nice!
