### ISSUE TITLE
Setup CI/CD

### ISSUE THREAD

**Issue by pnfcre** [ZEIW/ZEIW#14]
I learned about this amazing self-hosted deployment service called Exoframe.

Now I want to get started with it, so core team members no longer need to rely on internal bot commands to deploy ZEIW.

- [x] Wipe out my VPS
- [x] Install Docker & Exoframe
- [x] Setup Exoframe
- [x] Configure Travis CI

:boom: Boom. We have continious integration *and* continious delivery.

Now only thing left is to actually do this :see_no_evil:

**Comment by awildtalon** [comment]
What would be the difference in costs with OVH and Exoframe?

**Comment by pnfcre** [comment]
@awildtalon https://github.com/exoframejs/exoframe

**Comment by pnfcre** [comment]
Exoframe will be hosted on my OVH VPS.

**Comment by pnfcre** [comment]
There's no additional costs.

**Comment by awildtalon** [comment]
Ah okay. That's nice!

**Comment by pnfcre** [comment]
And we're done, CI/CD is now working perfectly!
