### ISSUE TITLE
Modal X button is very light and hard to see

### ISSUE THREAD

**Issue by Mippy** [ZEIW/ZEIW#22]
## Short Description

It's extremely hard to see the X button.

## Expected Result

Not hard to see.

## Actual Result

Hard to see.

## Steps to Reproduce

Step 1: Open modal
Step 2: Look

## System Settings

make me.

![image](https://user-images.githubusercontent.com/26975085/62002148-3832d200-b0b3-11e9-9382-8e46f079d396.png)

**Comment by pnfcre** [comment]
I'll fix this once I get a second :+1:
