### ISSUE TITLE
Return home button not working after rematch

### ISSUE THREAD

**Issue by pnfcre** [ZEIW/ZEIW#9]
![](https://user-images.githubusercontent.com/24176136/61039438-09d4a780-a3cf-11e9-92b9-ce910be7b847.gif)

## Description

Once you've rematched once, the "Return Home" button won't return you home.

## Expected Behavior

You should be returned home even after rematching once.

## Actual Behavior

You're not being returned home after rematching once.

## Steps to Reproduce

Step 1: Join a match with someone.
Step 2: Both players should rematch once game ends.
Step 3: Once the second match ends, click "Return Home".

## Your Environment

- Version used: -
- Browser Name and version: Chrome 75.0.3770.90
- Operating System and version: elementary 5.0 (64-bit)
- Link to your project: -

**Comment by Mippy** [comment]
Fixed in 1bf9b61.
